apiVersion: v1
kind: Service
metadata:
  name: triton-http
spec:
  selector:
    app: triton
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
    - protocol: TCP
      port: 8001
      targetPort: 8001
    - protocol: TCP
      port: 8002
      targetPort: 8002


